"""recreate tables2

Revision ID: b819aba299d2
Revises: 77a5dcebcd02
Create Date: 2026-04-28 15:21:52.819431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b819aba299d2'
down_revision: Union[str, Sequence[str], None] = '77a5dcebcd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This autogenerated revision duplicates tables created by earlier revisions.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
