"""recreate table

Revision ID: cc8e0f625b86
Revises: e17698aa7a34
Create Date: 2026-04-28 02:48:19.687943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc8e0f625b86'
down_revision: Union[str, Sequence[str], None] = 'e17698aa7a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The initial revision already creates `chunks`.
    # This autogenerated follow-up revision is intentionally a no-op.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
