version: '3'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


networks:
    backend:

volumes:
  mongodb_data:

